### ISSUE TITLE
Bug: format %2 without %1

### ISSUE THREAD

**Issue by OverlordZorn** [Crowdedlight/Crows-Electronic-Warfare#101]
https://github.com/Crowdedlight/Crows-Electronic-Warfare/blob/0b33e79ad86517f710344c3c07c31f31c6baafff/addons/zeus/functions/fnc_zeusRegister.sqf#L86

`diag_log format ["CrowsEW:fnc_zeusRegister: Zeus initialization complete. Zeus Enhanced Detected: %2",_hasZen];`

**Comment by diwako** [comment]
This is mainly an issue on current profiling branch which appears to not like this anymore
![image](https://github.com/user-attachments/assets/90e421b0-45d2-4d9d-adc5-7c2076d1c452)

**Comment by OverlordZorn** [comment]
SPEEDRUN GO MERGE 🤣

**Comment by b-mayr-1984** [comment]
> SPEEDRUN GO MERGE 🤣

Funny thing is I am not even at home on my PC.
I am lying on a picnic blanket in a park.

Thx for the report and the PR. 🙂

**Comment by OverlordZorn** [comment]
blame nomi, he encountered it and diwako saw the issue lul

**Comment by Crowdedlight** [comment]
Thanks for the Report and quick PR!

I have been abroad on vacation for the past 2 weeks ;-)
