### ISSUE TITLE
Spectrum Device Screen Completely Whited Out

### ISSUE THREAD

**Issue by jzpelaez** [Crowdedlight/Crows-Electronic-Warfare#109]
![107410_20240914113529_1](https://github.com/user-attachments/assets/ff8bf219-066e-4333-88e6-42b81f9d15c0)

As the title states, the screen on the spectrum device is whited out for certain UI elements.

I'd put the RPT log here, but GitHub doesn't seem to like attaching it.

I can send it over via Discord if need be.
Username: jzpelaez

I will see if reinstalling the mod may resolve the issue or not.

**Comment by jzpelaez** [comment]
![107410_20240914114821_1](https://github.com/user-attachments/assets/f1ee6704-640a-4ff5-a4b8-53b1eb80374c)

Forgot to post this in the initial- the error message that pops up.

**Comment by b-mayr-1984** [comment]
> I'd put the RPT log here, but GitHub doesn't seem to like attaching it.
> 
> I can send it over via Discord if need be. Username: jzpelaez

@jzpelaez try to upload the RPT log at https://gist.github.com/ and then provide a link here.

**Comment by jzpelaez** [comment]
Here we go.
https://gist.github.com/jzpelaez/1fac44e01a0b6c2405ba5a88475235d7

**Comment by b-mayr-1984** [comment]
> Here we go. https://gist.github.com/jzpelaez/1fac44e01a0b6c2405ba5a88475235d7

Could you try 2 things please:
1. test again without CrowsEW being in your active modset
2. test again with CrowsEW being the only mod active

Tell the outcome of either test.

I see that you have a ton of mods loaded and I just want to be sure there are no side effects with other mods.

**Comment by Crowdedlight** [comment]
We have seen it before. There Is Only War mod, breaks the screen. Not sure how but they overwrite the graphics used for that screen or something similar. I seem to recall it fucks with the titan/javalin screens too, but not 100% on that. 

I can't do anything about that as it's outside my control.

**Comment by jzpelaez** [comment]
Ah, that's just unfortunate.
