### ISSUE TITLE
anti-drone weapons

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#11]
Jammer weapon like DroneGun Tactical, that when aimed and locked on to drones will make them land where they are and loose connection to attached terminals? 

Should be doable to check for aim-line and some kind of lockon and then run scripts to make the drone land at position and disconnect from terminal.

**Comment by b-mayr-1984** [comment]
@Crowdedlight with your recent merge from `develop` to `main` this is done I think.

**Comment by Crowdedlight** [comment]
indeed. Rotary will try to land when jammed now. 

I am trying to gather together changelog notes for release one of the following days. But it will take a bit going through commits to double-check I didn't miss anything, as I merged all commits from your big PR, instead of squashing it 😅 

And rebase interactively is being annoying, so now I am just living with it and trawling the commit names to see if I missed something.
