### ISSUE TITLE
Jamming effect is sticking when deleting vehicles

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#113]
From discord dm:

> Hi there im with a Arma 3 unit that has been using you Mod in our recent Campaigns and FTX. Recently we have had an issue where if we destroy an asset with the Jammer modual attached to it the Jamming effect permanently effects the persons that were in the area when it was destroyed. traveling far away from the location dosnt seem to work either.
wanted to know if you had any fix for this or if we are doing something wrong on our side

> We have also observed that when a zues deletes an asset with the Jammer modual the jamming effect stays permanently in place.

**Comment by Crowdedlight** [comment]
[rpt_logs.zip](https://github.com/user-attachments/files/17575255/rpt_logs.zip)

**Comment by Crowdedlight** [comment]
The server log seems to have script errors reported in KAM. There is a chance that those errors in KAM stops execution of other code on the server that handles the clean-up of the jammers. 

```
15:42:25   Error then: Type Bool, expected if
15:42:25 File x\kat\addons\chemical\functions\fnc_breathing.sqf..., line 35
15:42:25 Error in expression <le["ace_medical_heartrate", 80] >= 105) then {
_unit say3D "kat_chemical_mask_br>
15:42:25   Error position: <then {
_unit say3D "kat_chemical_mask_br>
15:42:25   Error then: Type Bool, expected if
15:42:25 File x\kat\addons\chemical\functions\fnc_breathing.sqf..., line 35
15:42:25 Error in expression <le["ace_medical_heartrate", 80] >= 105) then {
_unit say3D "kat_chemical_mask_br>
15:42:25   Error position: <then {
_unit say3D "kat_chemical_mask_br>
```

Try to test if the jamming sticks in the same way when only running this mod, CBA3 and ZEN.

**Comment by Crowdedlight** [comment]
Never heard back. Assume the problem was fixed and caused by kat.

**Comment by AgentDove** [comment]
Problem caused by
https://github.com/Crowdedlight/Crows-Electronic-Warfare/blob/ee625d2dea642f6ac4d542d34bd40cd6c3339712/addons/main/functions/fnc_updateJammers.sqf#L35
not calling
[fnc_resetRadioIfDegraded.sqf](https://github.com/Crowdedlight/Crows-Electronic-Warfare/blob/main/addons/main/functions/fnc_resetRadioIfDegraded.sqf)
and instead calling old nonexistant function.
