### ISSUE TITLE
Error when trying to listen to a radio chatter

### ISSUE THREAD

**Issue by Yivas** [Crowdedlight/Crows-Electronic-Warfare#115]
When trying to use the spectrum device to listen to radio chatter, i get the following error:
![image](https://github.com/user-attachments/assets/0b14e044-6067-4143-a157-fd95a6df34ad)

**Comment by b-mayr-1984** [comment]
@Yivas can you please attach the RPT log file?

**Comment by Crowdedlight** [comment]
And please confirm if this happens with all radiochatter or a specific selection of selected pack etc? 

Would be helpful if you write the steps you used so we can easier recreate it and catch what is going on :)

**Comment by Yivas** [comment]
Only happens when using the British Voice Pack. Also i noticed another bug, in the voicepack list in the editor, the name of the police one doesnt appear
![image](https://github.com/user-attachments/assets/c5b7a335-c96e-46e9-b97c-14d93f78e8ea)
And here its my RPT log file
[Arma3_x64_2024-11-04_16-32-21.rpt.txt](https://github.com/user-attachments/files/17620459/Arma3_x64_2024-11-04_16-32-21.rpt.txt)

**Comment by Crowdedlight** [comment]
> Only happens when using the British Voice Pack. Also i noticed another bug, in the voicepack list in the editor, the name of the police one doesnt appear

Thank you for the info. The police radio does not show up as it was missing a key in the stringtable, so it was just a blank string. I have fixed that. Will try to investigate the script error/crash later tonight when I am home!

**Comment by Crowdedlight** [comment]
I had a bit of time to do a few quick tests. I can not reproduce the error you get. I tried to launch a test world with both the British and police radio pack, spawn in, equip the spectrum device with antenna for radio-stuff, and listen in. works perfectly fine on my end. 

The rpt you sent shows that the error seems to occur while still loading in, unless some messages in it got jumbled. But if it happens before you actually click "left-mouse" then it seems very wrong, as that part of the code should not be able to run unless you click left-mouse with the spectrum device attached. 

Would you be able to record a video of how you got this error? Like from the editor showing how you setup the module and all the way into the game where you get the error? 

It is very hard for me to find the error if I can't reproduce it on my own end. So I must be doing something different than you, when testing it.

**Comment by Crowdedlight** [comment]
hmm okay. The police pack not appearing will be fixed in next release. The "empty" spot in the drop-down is the police pack, so if you pick that you will get the police pack when you listen. It is just the display name that isn't shown. 

The intermittent issue makes it harder to debug and could potentially point at a scheduled code execution issue, as that function runs scheduled instead of unscheduled. 

If you get the script error again and have a way to reproduce it, please let me know so I can try and repeat it.

**Comment by Yivas** [comment]
Okay i will

**Comment by Crowdedlight** [comment]
Feel free to reopen this issue if it happens again.
