### ISSUE TITLE
Have TFAR Radio transmissions show up on their programmed frequency

### ISSUE THREAD

**Issue by RockDood** [Crowdedlight/Crows-Electronic-Warfare#14]
Being able to find an out post and such is pretty cool already. For PvP gamemodes, it would be really cool to be able to potentially find an enemy squad because they were using their radios too much. Bonus points if it already does this!

**Comment by Crowdedlight** [comment]
**notes for self:** 

Should be doable with modules to set ``missionSpace`` variables to turn it on and off as zeus. 

When turned on add eventhandler locally for ``OnTangent`` as: https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Events  

Not sure how to check when to remove signal again, but we can get frequency by ``tf_sw_frequency`` variable on unit. https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables 

Consider checking when unit stops talking https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Functions#TFAR_fnc_isSpeaking 
But could also give fake positive in cross-over. Although if we keep checking there should be a pause from radio communication to detect not talking and remove signal again.

**Comment by Crowdedlight** [comment]
Make missionSpace variable as array with the sides its active for. So like ``_arr = [west, east]`` and only add signals to sides active. 

Make enable/disable zeus module show select list and preload current active. So you can choose to only have it active for one side so you don't see your own frequencies. Or at least has the choice for that.

**Comment by Crowdedlight** [comment]
hmm. thought some more about it. As each frequency is unique across all players with multiple players using radios on same frequency, then it could be difficult to ensure its the same signal you look at. 
A way to try and avoid players "stealing" the signal from eachother while tracking could be to randomize the decimals? So frequency 120.xyz with xyz randomized. Would help avoid collisions.

**Comment by Crowdedlight** [comment]
- [ ] test to see if we need to enable event handler onTangent again on respawn, if so add it
- [ ] Test if "isSpeaking" is fired with DD or only radio? Do we detect the difference when radio is stopping broadcasting if player immediately talks in local? 
- [ ] add zeus module to toggle setting for enable/disable radioTracking
- [ ] add zeus module to be put on AI that in random intervals "broadcast" in random durations to be trackable. Should include a way for zeus to see what unit has it on, like a marker
- [ ] Add scan/action to the spectrum device. If used on signal from radio tracking, then play voice line sound etc. (might require rewrite to store beacons in hashmap

**Comment by Crowdedlight** [comment]
![image](https://user-images.githubusercontent.com/7889925/124648194-41c83580-de97-11eb-9ced-ee6cd092ac8a.png)

**Comment by Crowdedlight** [comment]
![image](https://user-images.githubusercontent.com/7889925/124650213-c5832180-de99-11eb-938a-40a1eb67c63c.png)

**Comment by Crowdedlight** [comment]
Move so chatter module to spawn or run on server. So if Zeus DC we don't loose the AI chatting. 

Use public var for chatter list? For easier jip without having events thrown around?

**Comment by Crowdedlight** [comment]
- [ ] overwrite display text of spectrum attachments to indicate the spectrum they actually covers?

**Comment by Crowdedlight** [comment]
added in develop, scheduled for release tomorrow
