### ISSUE TITLE
Berserker, issue with spectrum analyzer

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#23]

**Comment by Crowdedlight** [comment]
![image](https://user-images.githubusercontent.com/7889925/124977500-d619d000-e030-11eb-9557-c0a79e941685.png)

**Comment by Redux2021** [comment]
1. 
[Berserkers ARMA 3 Files.zip](https://github.com/Crowdedlight/Crows-Electronic-Warfare/files/6793534/Berserkers.ARMA.3.Files.zip)

**Comment by Redux2021** [comment]
Hey Crowdedlight, here are my (BERSERKER) Arma Files... if something is missing or you need more, send me a massage.
thanks for your help so far.

**Comment by Crowdedlight** [comment]
Don't see any obvious error in the logs. Mainly looking in the one where you only have the crows mods loaded. The bigger modpack seem to have multiple script errors made by the other mods. But as it doesn't work without those mods for you, it is probably not a mod conflict. 

Are you using the same map/template to test each time? If so can you share it? 

I have tried to test it on VR, Altis and without TFAR so exact same mods loaded as you had. All works fine for me in SP and hosted. 

I really don't know what's going on, or what you are doing differently, but I cannot reproduce your error of it not working. Last resort could be if you recorded exactly how you tested and used it on video and put it on youtube and gave me a link. Might be able to spot if you are doing something different. But otherwise, I really not sure how to further help.

**Comment by Redux2021** [comment]
i testet it each time on the same map :-(
if i have some time i will send you the files or record you a video.

thank you for helping me

**Comment by Redux2021** [comment]
[Spectrum Test.Enoch.zip](https://github.com/Crowdedlight/Crows-Electronic-Warfare/files/6873661/Spectrum.Test.Enoch.zip)

**Comment by Redux2021** [comment]
https://www.dropbox.com/s/kcxuvz1z3o9j92o/20210725_080744.mp4?dl=0

**Comment by Redux2021** [comment]
sorry for video quality... after vacation my video camera was unloaded...

**Comment by Crowdedlight** [comment]
Sorry for the late answer, but have been on vacation. 

I noticed you had Contact enabled under DLC? 
Try to launch the game without the Contact DLC enabled. 

Contact goes in and takes over and adds more feature to the spectrum signal device, which means the base-game API to it, which I use, do not work in the same way. 

This mod is not dependent on having contact DLC loaded, as the assets, maps and basic APIs are all in base-game. Loading with Contact is more geared towards the single-player campaign and contact specific scenarios, as it enables and overwrites parts of the base game to create the contact experience.

**Comment by Redux2021** [comment]
Amazing it works! thanks for your help :-)

**Comment by Crowdedlight** [comment]
Glad you got it working!
