### ISSUE TITLE
heartbeat / movement sensor. 

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#32]
Perhaps custom antenna to spectrum device that gives custom gui in a kind of "forward" sensor model. Where it shows dots for detected enemies in a 180deg fan infront of you

**Comment by Zhasik0901** [comment]
Something like this already in new CDLC "WSahara" - in VRANA ION VR showcase
[] call lxWS_fnc_showSensor;  - enable
["Exit"] call (uiNamespace getvariable "lxWS_fnc_showSensor"); - disable

![image](https://user-images.githubusercontent.com/61241810/143770293-12c14998-c99f-4d4b-a38d-63c558ef332d.png)
