### ISSUE TITLE
3DEN Editor Modules for Spectrum Signal entities.

### ISSUE THREAD

**Issue by RockDood** [Crowdedlight/Crows-Electronic-Warfare#34]
Currently have to place all Spectrum sources after the mission has started which either would make SP missions unable to use signal tracking or delay starting a mission because a Zeus must do all spectrum setup after mission has been initialized.

**Comment by Crowdedlight** [comment]
Due to increasing limited spare-time and that I haven't looked into making modules available in eden and the complications that comes with it. Its unlikely for this to be added in the short term. 

However you should be able to add it to a unit in the editor by using this script in the missions ``initServer.sqf``. Then name the unit in the editor like "signalSource1" and use ``signalSource1`` instead of ``_unit`` in the script.  

```sqf
//_unit: the unit you which to add. You can give the unit a variable name in editor and use that. 
//_freq: Frequency to set signal on. Has to be within range of the antenna frequencies
//_range: The range the signal is transmitted in meters
//type: text that say what type it is. Use the default set "zeus". 
["crowsEW_spectrum_addBeacon", [_unit, _freq, _range, "zeus"]] call CBA_fnc_globalEventJIP;
```

**Comment by RockDood** [comment]
Even this is still a huge time save with signal tracking setup! Much appreciated with all effort so far!

A similar description for scripting out radio chatter would be the other half of the time save for those that want to have a good amount of signals to track right from the start. No rush though as this is still solid work none-the-less.

**Comment by Crowdedlight** [comment]
You should be able to do the same with radio chatter. This should be run only once. (So Eden init fields of the unit, won't work, as it gets run once per player and would give you duplicates). Its the same as with spectrum signals. Put it in the ``initServer.sqf`` would probably be the best approach. 

```sqf
//_unit: the unit you which to add. You can give the unit a variable name in editor and use that. 
//_range: The range the signal is transmitted in meters
//_pauseMin: Minimum time in seconds to pause between broadcasts
//_pauseMax: Maximum time in seconds to pause between broadcasts
//_durationMin: Minimum time in seconds to broadcasts
//_durationMax: Maximum time in seconds to broadcasts
//_freqMin: lower limit of random frequency used
//_freqMax: upper limit of random frequency used. (frequency used will be within this interval)
//_voicePack: The voicepack to use when people listen to it. 
["crowsEW_spectrum_addRandomRadioTrackingChatter", [_unit, _range, [_pauseMin, _pauseMax], [_durationMin, _durationMax], [_freqMin, _freqMax], _voicePack]] call CBA_fnc_serverEvent;
```

The available voicepacks are on of the following strings. It has to be the exact naming and capitalisation as shown, as they are used as keys for lookup. 
```sqf
["british", "morsecode", "electronic", "alienElectronic", "police"]
```

**Comment by Crowdedlight** [comment]
Editor modules for most features was added in 1.4.0. Closing issue.
