### ISSUE TITLE
Electronic Warfare TFAR

### ISSUE THREAD

**Issue by Longshot133** [Crowdedlight/Crows-Electronic-Warfare#38]
Hello, I was just wondering how to make the modules work with TFAR we are currently using the older version instead of TFAR Beta and was wondering if it worked as well. In Addition is there anyway to add sounds to the sound modules?

**Comment by Crowdedlight** [comment]
So it has not been tested with the "old tfar" although only a few functions should break. The TFAR Jammer and listening in using the spectrum device I believe should still work, but the disabling of radios when using EMP will not work. 

My best advice if you are forced to use "old tfar" is to try it out and see what works for you. I only know that EMP part will not work as that relies on code added to TFAR beta. 

No, the sounds are packed with the mod as its required that every player on the server have the same sounds. So, unfortunately, no way for users to add their own sounds.
