### ISSUE TITLE
Zeus Not Showing "Crows Electronic Warfare" Tab

### ISSUE THREAD

**Issue by TeamRDDBCoreCM** [Crowdedlight/Crows-Electronic-Warfare#40]
For the Odd reason when I have the Mod Enabled I saw it once in the Zeus tab when it was working before like 10 mins ago but once I went to try and use it again in the same scenario it just vanished from even accessing it like it was never there.

I don't know if this is just persisting with only me or others are having the same issues.

**Comment by Crowdedlight** [comment]
If you see experience that, can you try to go in and out of zeus interface? There is a race-condition issue that can happen where the modules doesn't get registered before you go into the interface. A refresh of the interface by going out of zeus and back into it usually fixes it.

**Comment by TeamRDDBCoreCM** [comment]
Already tried that method as I know how Zeus Works with Modules but the odd part was that it showed up literally there at the start of a mission with friends & when I tried to use it in the same mission as Zeus it disappeared & I couldn't find out why

**Comment by Crowdedlight** [comment]
That is very odd. Would you be able to send your .rpt file from that session? 

Not something I have experienced before or heard other experience. 
Was Zeus Enhanced modules still available when it happened?

**Comment by SigmaPopsi** [comment]
can confirm, got the same issue right now, its not showing up in the modules tab.

heres the RPT file, its in zip since github doesnt support rpt
[Arma3_x64_2022-07-01_11-55-19.zip](https://github.com/Crowdedlight/Crows-Electronic-Warfare/files/9027959/Arma3_x64_2022-07-01_11-55-19.zip)
t

**Comment by SigmaPopsi** [comment]
i loaded ACE, CBA, Zeus Enchanced and ACE and it worked, the only problem is when i unload the DiGi ace extension mod and i run arma on zeus mode, i still cant see the modules. It used to work before adding the DiGi Mod. Got any idea what may cause this?
[Arma3_x64_2022-07-01_20-02-26.zip](https://github.com/Crowdedlight/Crows-Electronic-Warfare/files/9030870/Arma3_x64_2022-07-01_20-02-26.zip)

**Comment by SigmaPopsi** [comment]
nevermind, i have no idea how but it works on my clan's server, it just wouldnt work on local, but still thanks for helping me out

**Comment by Crowdedlight** [comment]
I don't see any particular errors in that rpt log. It appears as my mod loads correctly and registers the zeus modules. Did you by chance have forced interface turned on? Sometimes there can be an issue with Zeus Enhanced loading the modules and you need to go out of zeus interface and back in. (hit y twice). 

Otherwise my best bet is another mod is somehow interfering with the loading of zeus modules as it works with the mods I said alone. So you could try to keep unloading mods until you find which one is the problem.

**Comment by SigmaPopsi** [comment]
okay, thank you for help, not forcing the zeus module helped me with it, cheers mate.
