### ISSUE TITLE
Dependency to ACE3 (and zen_compat_ace) not listed

### ISSUE THREAD

**Issue by b-mayr-1984** [Crowdedlight/Crows-Electronic-Warfare#55]
These are the dependencies that `Crows-Electronic-Warfare` is listing in the launcher:
![image](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/76476468/eb7cf330-e929-4eb1-9599-67807bbf6cad)

When trying the test mission `dev_mini.Enoch` an additional dependency on [ACE3](https://steamcommunity.com/sharedfiles/filedetails/?id=463939057) is shown.

![image](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/76476468/244aa324-ed23-40a0-8ce6-22fe1c9f7e7a)

After adding ACE3 the test mission loads just fine. 🙂 

I believe not only the test mission is dependent on ACE3 but also item attachment like C-Track.

Tested version:
![image](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/76476468/9dece69b-0637-4e17-8a66-cdd7e62803e6)

**Comment by b-mayr-1984** [comment]
I just noticed during testing, that with the addition of ACE3 also comes the need for [ zen_compat_ace](https://steamcommunity.com/sharedfiles/filedetails/?id=2018593688).

`19:48:47 WARNING: zen requires zen_compat_ace (@ACE) at version [1,14,0,34] (or higher). You have none.`

After adding this mod, I don't get any mod warning in the RPT file anymore. 🙂

**Comment by Crowdedlight** [comment]
The mod has intergrations with ACE but should not depend on it. It is set to register if ACE is loaded and only then use functions from ACE. 

The test-mission is faulty, which is my bad. Problem being that when you test the mission with ace and use the editor it tend to automatically save the changes and then believe it needs ACE. Even if you originally made the mission without ACE. #ArmaEditorThings 

You should be able to select "load anyway" on the mission and continue fine. But I will have a look at de-aceifying the mission again. 

C-Track is made to not require ACE, but works better with ACE. If ACE is loaded the mod registers it and use the ace attachment system. If ACE is not loaded it uses default scroll-wheel options. Tested to work with both.

**Comment by Crowdedlight** [comment]
I believe this was fixed when I updated the test mission. In anycase the "load anyway" button should work without any negative effects.
