### ISSUE TITLE
Add setting for self-tracking

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#69]
I can see where you are coming from with a much higher focus on simulation than "arcade". I am personally probably a bit more in the middle. While I do like some simulation, I also don't want the game to turn into something as "cumbersome" (lack of better word) as irl/work, as then its not something the average player would use in a hurry as a fun element. And it can easier become confusing or less intuitive for players without the domain knowledge of RF. I could easily see more casual players reporting it as a bug or be frustrated, if they had a signal on them, and it meant they had a constant high signal that hid other jammable signals in that frequency.

But I also get the interest of being able to simulate and let players discover if they are being tracked or are broadcasting RF.

I think the best compromise is to make a CBA setting that enables/disables being able to see your own signal sources. Then you can use that and the "tfar_sidetrack" setting to determine how far you want to go simulation versus making it a more casual game element. As one setting decides if you can see your own signals, and the other if you can see friendly radio signals.

**Comment by b-mayr-1984** [comment]
> @b-mayr-1984 Right now you can only self-track TFAR if you enable both the "track same side", and "self-track" CBA settings. As each would hide your own signature.
> 
> Not sure if that makes sense, as you would somewhat expect "self-tracking" enabled, to always show your own signature, even if "track friendly signals" are turned off?

If the tooltip of `selfTracking` states that it is dependent in the other option being `true` I guess it is fine and an understandable dependency.
