### ISSUE TITLE
Gaps in frequency coverage for TFAR SR radios

### ISSUE THREAD

**Issue by b-mayr-1984** [Crowdedlight/Crows-Electronic-Warfare#75]
TFAR shortrange radios can be set to as high as 512MHz frequency.
(see https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/addons/core/defines.hpp#L32)

But the Spectrum Device can monitor at most up to 500MHz when using the experimental antenna.
![image](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/76476468/067f3596-16d6-4985-84ce-469cba0d8647)

Even transmissions at 500MHz straight are not shown. 
So to make 512MHz visible I **recommend modifying the Experimental Antenna to go up to 513MHz**.

(NOTE that the left-most frequency boundaries are not truncated. So extension to lower than 30MHz (with MIL antenna) is not necessary)

For COOP missions this is probably irrelevant, but for TvT it is essential to have it because competitive players usually try to gain every edge they can find. And by simple change of frequency they could avoid detection by electronic warfare operators.

**Comment by b-mayr-1984** [comment]
The same problem exists between 389 and 390 MHz. 
In this gap neither MIL- nor experimental antenna cover transmissions that happen there.
![image](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/76476468/5c4b4cb9-5e51-49c9-bc22-da21565651af)

**Comment by Crowdedlight** [comment]
Makes sense. Would need to check if I can just extend the config on the antennas or if the limit of frequency is hardcoded into the spectrum device api. As I can't change BIs code if they don't support showing frequencies higher. (I hope they don't care about max, but just have it set per config, but simply can't remember from top of head)
 
Can have a look at what is possible when I am home next week.

**Comment by b-mayr-1984** [comment]
> Edit: For the 389-390 gap I propose to just change jammer antenna to be 390 inclusive.

I don't recommend that, because the jammer antenna has a different implementation for left-click, compared to TFAR tracking with ICOM device. 
This would make the behavior inconsistent IMHO. 🤔

**Comment by Crowdedlight** [comment]
> I don't recommend that, because the jammer antenna has a different implementation for left-click, compared to TFAR tracking with ICOM device. This would make the behavior inconsistent IMHO. 🤔

Ah yes, I was thinking the tfar military antenna be changed to 390. Wrote jammer by mistake 😓 
So it just moves from 389 to 390. Then have the experimental antenna cover the upper band. The only downside to that is that you wouldn't be able to listen in with the experimental antenna. Only track. So TvT players would then likely always use 391+ frequencies to avoid being listened to. 

The balanced solution would then be to set military radio, (TFAR one) to be 30-513 MHz. However that is a wide span and makes the experimental antenna completely superfluous as the military one would then be able to take all current signal sources frequencies. 

I guess it might make sense to do a total rebalance of frequencies, if possible. So then bump experimental to be above 513 MHz, and be dedicated to signals added by zeus/C-tracker/C-motion. And have jammer antenna spectrum be where it is. Would give each antenna it is own purpose and frequencies. 

If it would cover up to 1090 MHz then it would cover the frequency used for ADSB/Mode S Transponder for aircraft and could potentially be implemented to track responses from secondary radars or ADSB transmitters. However that was just a sudden idea. (Like an antenna parabola if wanting to push into sat com at 2-4GHz ranges)

A completely different approach could also be to add more variants of antennas. Reuse the 3D models (I am not good enough for those complex modeling tasks), but change the name, config and ranges. Split the 30-513MHz into two different antennas, potentially. Would give more play around which antenna are you checking with and occasional comms changes between frequency bands. 

Honestly I am not sure what I think would be best and least negative effects. I am leaning more to bumping the experimental to above 513MHz if possible, letting it have a range up there and giving each antenna it's own frequency range in that way.

**Comment by b-mayr-1984** [comment]
> [..] moves from 389 to 390. Then have the experimental antenna cover the upper band. The only downside to that is that you wouldn't be able to listen in with the experimental antenna. Only track. [..]

Is there a reason why the Experimental Antenna does not support listening in? Does it have another _unique ability_?

> The balanced solution would then be to set military radio, (TFAR one) to be 30-513 MHz. 

I like the consistency of that. 
Also the gameplay is then more straight forward without need to potentially change antennas back and forth constantly.

> However that is a wide span and makes the experimental antenna completely superfluous as the military one would then be able to take all current signal sources frequencies.
> 
> I guess it might make sense to do a total rebalance of frequencies, if possible. So then bump experimental to be above 513 MHz, and be dedicated to signals added by zeus/C-tracker/C-motion. And have jammer antenna spectrum be where it is. Would give each antenna it is own purpose and frequencies.

Gameplay-wise I love the idea that every antenna has it's unique purpose. And yes
- 1x for TFAR
- 1x for jamming
- 1x for other applications (like you mentioned above)

would make sense.

> If it would cover up to 1090 MHz then it would cover the frequency used for ADSB/Mode S Transponder for aircraft and could potentially be implemented to track responses from secondary radars or ADSB transmitters. However that was just a sudden idea. (Like an antenna parabola if wanting to push into sat com at 2-4GHz ranges)
> 
> A completely different approach could also be to add more variants of antennas. Reuse the 3D models (I am not good enough for those complex modeling tasks), but change the name, config and ranges. Split the 30-513MHz into two different antennas, potentially. Would give more play around which antenna are you checking with and occasional comms changes between frequency bands.

Sounds like a lot of changes given the initial scope of the issue.
So I would put this on the stack _ideas for future reference_.

> Honestly I am not sure what I think would be best and least negative effects. I am leaning more to bumping the experimental to above 513MHz if possible, letting it have a range up there and giving each antenna it's own frequency range in that way.

I am fine with that. 
But then I recommend that the Experimental Antenna is also made compatible with the ICOM device. Otherwise there is still an **inconsistency** and in TvT scenarios everyone with an SR radio would just avoid the range of the MIL antenna.

If you prefer **uniqueness** then bumping the MIL antenna would be the way to go.

**Comment by Crowdedlight** [comment]
I think I expressed me poorly. The solution I am leaning to is:

30-513MHz for military antenna, for TFAR tracking,  
433-445 for jammer antenna (Extended it a bit to not have the jamming band too narrow, 7 MHz before was quite small)  
520-1090 MHz, Experimental antenna, moving C-track, Zeus signals etc. to that range)  

To, as you say, give them uniqueness.

**Comment by b-mayr-1984** [comment]
> I think I expressed myself poorly. The solution I am leaning to is:
> 
> 30-513MHz for military antenna, for TFAR tracking, 433-445 for jammer antenna (Extended it a bit to not have the jamming band too narrow, 7 MHz before was quite small) 520-1090 MHz, Experimental antenna, moving C-track, Zeus signals etc. to that range)
> 
> To, as you say, give them uniqueness.

I support all of this. 🙂

**Comment by Crowdedlight** [comment]
Should be fixed with #77
