### ISSUE TITLE
Modules Not Working

### ISSUE THREAD

**Issue by BlackbirdAter** [Crowdedlight/Crows-Electronic-Warfare#90]
As per my message on the workshop, ever since the update, I have not been able to use several modules, including the Add Signal Source and Add Jammer (both in Eden & Zeus). I have used these several times in the past without issue, but I cannot use it on several maps, and several mission-makers are having the same issue.

I am not sure if there is a new conflict after the recent update. I cannot attach our mod Pack .html file due to GitHub restrictions, so I included the list below. Maybe you can help me identify conflicting mods, and I can see if those mods are causing issues after being removed.

**MOD LIST**
121St Special Forces Mod Pack
CBA_A3
ace
RHSUSAF
RHSAFRF
CUP Weapons
RHSGREF
Remove stamina
Zeus Enhanced
Tier One Weapons
CUP Units
SCP - Regalis's Containment Breach Assets
Hatchet Framework - Stable Version
Advanced Rappelling - Reworked
Advanced Sling Loading
Advanced Towing
Advanced Urban Rappelling
ArmA 3 Custom Buildings - Original
BackpackOnChest
Crows Electronic Warfare
CUP Terrains - Core
POLPOX's Base Functions
Custom User Textures (Read-Desc)
Digital Kompass
DUI - Squad Radar
Em_Buildings
Enhanced Movement
ILBE Assault Pack - Rewrite
LAMBS_Danger.fsm
Military Gear Pack
Project OPFOR
Reduced Weapon Sway
Remove stamina - ACE 3
Task Force Arrowhead Radio (BETA!!!)
TFAR Animations
Tier One Weapons Optics NVG Compatibility
Turret Enhanced
Uriki's Mission Items
WebKnight Flashlights and Headlamps
ZEPHIK Female Units V2
Zeus Enhanced - ACE3 Compatibility
Zeus Immersion Sounds
Zulu Headless Client (ZHC)
CH View Distance
Weather Plus
[EM] Gendarmerie 2035 (v2)
M113A3 Gendarmerie Retexture
Uriki's Ballistic Mask
Uriki's Mask Mod
PLP All in One
ArmA Containment Breach - Music & Sounds
LAMBS_RPG
LAMBS_Suppression
RHSTERRACORE
CUP Terrains - Maps
Interiors for CUP
Hate's Digital Camera
DEGA: LPD Liberty Modification
@Horror_Mod
Eden Objects
Eden Extended Objects
Task Force 373 MH-47G SOAR Chinook
GRAD Civilians
[CYTECH] Core Assets And Functions
SCP : Dollhouse Bandana Retextures
SCP Extended Functions
Improved Melee System
Weapon Light Improvement - Tier One Weapons
Hatchet H-60 pack - Stable Version
Swim Faster
Kunduz River
Jbad
Immersion Cigs
AI Cannot See Small Drones
121St Special Forces Music Pack
ACE 3 Extension (Animations and Actions)
Breach
Gruppe Adler Trenches
CUP Vehicles
UMB Colombia
BFM - Maps
Sa'hatra
IEDD Notebook
EOD Suit Compatible with IEDD Notebook
F.U.S.E -- EOD & Explosives Project

**Comment by Crowdedlight** [comment]
Could you please attach an rpt log from an attempt where it does not work? 
And would you be able to confirm if you can use the modules if you only load CBA, ZEN and this mod? 

It would help me narrow it down, as I can not reproduce the error myself. 

![billede](https://github.com/Crowdedlight/Crows-Electronic-Warfare/assets/7889925/eb2ed441-5570-4398-b58b-0cdc5a5ea9b1)

**Comment by Crowdedlight** [comment]
And when you say "can't use", in what way? Does the module not show for you, can you put it down and click ok but nothing happens? 

I need more details about the error here :)

**Comment by Crowdedlight** [comment]
stale. Reopen with requested information if still an issue.
