### ISSUE TITLE
add stringtable

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Electronic-Warfare#95]

**Comment by Huzy1018** [comment]
Hi bro, when can we add other languages

**Comment by Crowdedlight** [comment]
when I have tested #96 and merged it. Might have time to do that tomorrow.

**Comment by Crowdedlight** [comment]
its merged now. So feel free to add languages to the stringtables. Can recommend using https://github.com/bux/tabler. 

Currently the string tables only contain english.
